/** Centralized cache durations for MotoGP PulseLive data. */
export const CACHE = {
  MOTOGP_STANDINGS: 300,
  MOTOGP_SCHEDULE: 3600,
  MOTOGP_SCHEDULE_MEMORY_SEC: 300,
  MOTOGP_HISTORY: 3600,
  MOTOGP_PROFILES: 86400,
  MOTOGP_SESSION_RESULTS: 300,
} as const;

export const MOTOGP_SCHEDULE_MEMORY_MS =
  CACHE.MOTOGP_SCHEDULE_MEMORY_SEC * 1000;
